/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opposite.number;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {
    @Test void oppositeTest() {
        assertEquals(0, App.opposite(0));
        System.out.println(App.opposite(0));

        assertEquals(1, App.opposite(-1));
        System.out.println(App.opposite(-1));

        assertEquals(-14, App.opposite(14));
        System.out.println(App.opposite(14));

        assertEquals(34, App.opposite(-34));
        System.out.println(App.opposite(-34));
    }
}
