/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package opposite.number;

public class App {
    public static void main(String[] args) {
        System.out.println(opposite(1));
    }

    static int opposite(int number) {
        return -number;
    }

}
